language: ruby
rvm:
  - 1.9.x
  - 2.0.x
  - 2.1.x
  - 2.2.x
  - 2.3.x
  - 2.4.x
before_script:
  - mysql -e 'create database database_cleaner_test;'
  - psql -c 'create database database_cleaner_test;' -U postgres
  - cp db/sample.config.yml db/config.yml
script:
  - bundle exec rspec
gemfile:
  - Gemfile
before_install:
  - gem install bundler -v 1.14.6
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.3.3-unix.tar.gz
  - tar -xzf neo4j-community-2.3.3-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.3.3/conf/neo4j-server.properties
  - neo4j-community-2.3.3/bin/neo4j start
services:
  - redis-server
  - mongodb
